config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations',
    passwords: 'admins/passwords'
  }

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Ckeditor::Engine => '/ckeditor'

  get 'user_wellcome' => 'users#wellcome'
  
  resources :users do
    resources :user_notifications
    resources :user_follows
  end
  
  resources :posts do
    resources :post_votes
    resources :post_follows
    resources :post_comments
    resources :post_reports
  end

  resources :post_comments do
    resources :post_comment_votes
    resources :post_comment_reports
  end

  resources :categories do
    resources :topics
  end

  resources :topics do
    resources :topic_follows
    resources :topic_reports
  end

  resources :post_comments do
    resources :post_comments
  end

  resources :pages

  resources :scrapers

  get 'page_search' => 'pages#search'
  root "pages#home"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/topic.rb
class Topic < ApplicationRecord
    extend FriendlyId
    def convert_slug
        slug = name.downcase.to_s
        slug.gsub! /[àáạãảâậấẫầẩăặắằẵẳ]/, "a"
        slug.gsub! /[đ]/, "d"
        slug.gsub! /[èéẹẽẻêềếệễể]/, "e"
        slug.gsub! /[óòọõỏôốồộỗổơớợỡờở]/, "o"
        slug.gsub! /[úùụũủưứựừữử]/, "u"
        slug.gsub! /[íịìĩỉ]/, "i"
        slug.gsub! /[ýỵỹỳỷ]/, "y"
        return slug
    end
    friendly_id :convert_slug, use: :slugged
    
	mount_uploader :avatar, ImageUploader
	mount_uploader :cover_image, ImageUploader
	
	has_many :topings
  	has_many :posts, through: :topings
      
  	has_many :topic_follows, dependent: :destroy
    has_many :topic_reports, dependent: :destroy

    belongs_to :category, optional: true

	def self.search(search)
        if search
            target_search = Topic.where("name ILIKE?", "%#{search}%")
            if(target_search)
                self.where(id: target_search)
            end
        end
    end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
	include PostsHelper
	include TopicsHelper
    before_action :require_login, only: [:new, :create, :edit, :update, :destroy]
	before_action :set_topic, only: %i[ show edit update destroy ]

	def index
		@topics = Topic.all.page(params[:page]).per(20)
	end

	def show
		@topic_posts = @topic.posts

		@tab_id = "default"
	    if(params.has_key?(:tab_id))
	        @tab_id = params[:tab_id]
	    end

		if "default" == @tab_id || "TopicPostForYou" == @tab_id
			@buffers = @topic_posts.sort_by{|post| cal_post_hot_point(post)}.reverse
			@posts = Kaminari.paginate_array(@buffers).page(params[:page]).per(10)
		end
	
		if "TopicPostTrendID" == @tab_id
			@buffers = @topic_posts.sort_by{|post| cal_post_trend_point(post)}.reverse
			@posts = Kaminari.paginate_array(@buffers).page(params[:page]).per(10)
		end
	
		if "TopicPostNewID" == @tab_id
      		@posts = @topic_posts.order('created_at DESC').page(params[:page]).per(10)
		end
	
		if "TopicPostTopID" == @tab_id
			@buffers = @topic_posts.sort_by{|post| cal_post_top_point(post)}.reverse
			@posts = Kaminari.paginate_array(@buffers).page(params[:page]).per(10)
		end
	
		if "TopicPostTopWeekID" == @tab_id
			# @buffers = @topic_posts.where("created_at >= ?", 1.week.ago.utc)
			@buffers = @buffers.sort_by{|post| cal_post_top_point(post)}.reverse
			@posts = Kaminari.paginate_array(@buffers).page(params[:page]).per(10)
		end
	
		if "TopicPostTopMonthID" == @tab_id
			# @buffers = @topic_posts.where("created_at >= ?", 1.month.ago.utc)
			@buffers = @buffers.sort_by{|post| cal_post_top_point(post)}.reverse
			@posts = Kaminari.paginate_array(@buffers).page(params[:page]).per(10)
		end
	
		if "TopicPostTopYearID" == @tab_id
			# @buffers = @topic_posts.where("created_at >= ?", 1.year.ago.utc)
			@buffers = @buffers.sort_by{|post| cal_post_top_point(post)}.reverse
			@posts = Kaminari.paginate_array(@buffers).page(params[:page]).per(10)
		end
	
		if "TopicPostPodID" == @tab_id
			@buffers = @topic_posts.where("podcast <> ''")
			@buffers = @buffers.sort_by{|post| cal_post_trend_point(post)}.reverse
			@posts = Kaminari.paginate_array(@buffers).page(params[:page]).per(10)
		end
		
        @topic_relateds = Topic.all.reject{|i| i.id == @topic.id}
        @topic_relateds = @topic_relateds.sort_by{|topic| cal_topic_trend_point(topic)}.reverse.first(10)
	end

	def new
		@topic = Topic.new
	end	

	def create
		@topic = Topic.new(topic_params)
		@topic.user_id = current_user.id
	    if @topic.save
	      	redirect_to categories_path
	    end
	end

	def update
	end

	def destroy
	end

private
	def topic_params
      	params.require(:topic).permit(:name, :description, :avatar, :cover_image, :category_id)
    end

	def set_topic
      	@topic = Topic.friendly.find(params[:id])
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
    def cal_topic_trend_point(topic)
        topic_follow_count = topic.topic_follows.count
        return topic_follow_count
    end
end

app/views/topics/_form.html.erb
<div class="new_topic_form">
    <div class="container">
        <div class="row">
            <div class="col-sm-8 col-nopadding">
	            <div class="new_topic_title">
	                <%if !@is_edit%>
	                    <a>Thêm chủ đề mới</a>
	                <%else%>
	                    <a>Update <%=@topic.name%></a>
	                <%end%>
	            </div>

	            <%= form_for @topic, :html => { :class => "form-horizontal topic" } do |f| %>
		            <div class="new_topic_section">
		                <div class="new_topic_content">
							<div class="new_topic_label">
								<a><%= f.label :name, "Tên chủ đề", class: "new_topic_label_name" %></a>
							</div>
		                    <div class="new_topic_input">
		                        <%= f.text_field :name,  autofocus: true, :required => true, class: "form-control", placeholder: "Ex: Khoa học công nghệ..." %>
		                    </div>
		                </div>
						<div class="new_topic_content">
							<div class="new_topic_label">
								<a><%= f.label :description, "Mô tả", class: "new_topic_label_name" %></a>
							</div>
		                    <div class="new_topic_input">
		                        <%= f.text_area :description, :required => true, class: "form-control-rich-text", placeholder: "Nội dung" %>
		                    </div>
		                </div>
		            </div>

					<div class="new_topic_section">
						<div class="new_topic_content">
							<div class="new_topic_label">
								<a><%= f.label :category_id, "Chọn danh mục phù hợp với chủ đề của bạn", class: "new_topic_label_name" %></a>
							</div>

							<div class="new_topic_input">
								<%= f.select :category_id, Category.all.collect {|m| [m.name, m.id]},{}, class: "form-control"%>
							</div>
						</div>
					</div>

					<div class="new_topic_section">
						<div class="new_topic_content">
							<div class="new_topic_label">
								<a><%= f.label :avatar, "Ảnh đại diện", class: "new_topic_label_name" %></a>
							</div>
		                    <div class="new_topic_input">
		                        <%= f.file_field :avatar, :required => true, class: "form-control"%>
		                    </div>
		                </div>

						<div class="new_topic_content">
							<div class="new_topic_label">
								<a><%= f.label :cover_image, "Ảnh bìa (nếu có)", class: "new_topic_label_name" %></a>
							</div>
		                    <div class="new_topic_input">
		                        <%= f.file_field :cover_image, class: "form-control"%>
		                    </div>
		                </div>
		            </div>

		            <div class="new_topic_submit">
		                <%= f.submit "Submit", class: "new_topic_form_submit" %>
		            </div>
		        <%end%>	
	        </div>
        </div>  
    </div>
</div>

app/views/topics/_topic.html.erb
<%if mini_tyle == true%>
    <div class='topic_mini_index_block'>
        <%if topic.avatar?%>
            <div class='topic_mini_index_topic_avatar'>
                <%= link_to (image_tag(topic.avatar.url)), image_path(url_for(topic.avatar.url)), rel: "gallery" , :href => topic_path(topic)%>
            </div>
        <%else%>
            <div class='topic_mini_index_topic_avatar'>
                <%= link_to (image_tag("default-avartar.jpg")), image_path(url_for("default-avartar.jpg")), rel: "gallery" , :href => topic_path(topic)%>
            </div>
        <%end%>
        <div class='topic_mini_index_topic_block'>
            <div class='topic_mini_index_topic_name_block'>
                <a><%= link_to (truncate(strip_tags(topic.name), length: 50)), topic_path(topic) %></a>
            </div>

            <div class='topic_mini_index_topic_nickname_block'>
                <span><%=topic.category.name%></span>
            </div>

            <div class="topic_mini_index_topic_follow_block" id="topic_follow_<%=topic.id%>">
                <%if user_signed_in?%>
                    <% pre_follow = topic.topic_follows.find { |follow| follow.user_id == current_user.id} %>
                    <% if pre_follow %>  
                        <%= button_to topic_topic_follow_path(topic, pre_follow, type_param: 'index'), method: :delete, remote: true , form_class: "btn_highlight" do%>
                            <a>Đang theo dõi</a>
                        <%end%> 
                    <%else%>
                        <%= button_to topic_topic_follows_path(topic, type_param: 'index'), method: :topic, remote: true, form_class: "btn_normal" do%>
                            <a>Theo dõi</a>
                        <%end%> 
                    <%end%>
                <%else%>
                    <button type="button" class="btn_normal" data-toggle="modal" data-target="#buttonModalLoginCenter">
                        <a>Theo dõi</a>
                    </button>
                <%end%>
            </div>
        </div>
    </div>
<%else%>
    <div class='topic_index_block' id="topic_index_<%=topic.id%>">
        <%if topic.cover_image?%>
            <div class='topic_index_cover'>
                <%= link_to (image_tag(topic.cover_image.url)), image_path(url_for(topic.cover_image.url)), rel: "gallery" , :href => topic_path(topic)%>
            </div>
        <%else%>
            <div class='topic_index_cover'>
                <%= link_to (image_tag("default-cover.jpg")), image_path(url_for("default-cover.jpg")), rel: "gallery" , :href => topic_path(topic)%>
            </div>
        <%end%>

        <%if topic.avatar?%>
            <div class='topic_index_avatar'>
                <%= link_to (image_tag(topic.avatar.url)), image_path(url_for(topic.avatar.url)), rel: "gallery" , :href => topic_path(topic)%>
            </div>
        <%else%>
            <div class='topic_index_avatar'>
                <%= link_to (image_tag("default-avartar.jpg")), image_path(url_for("default-avartar.jpg")), rel: "gallery" , :href => topic_path(topic)%>
            </div>
        <%end%>

        <div class='topic_index_info_action'>
            <button class="topic_index_close_btn" onclick="myFunctionCloseTopic('topic_index_' + <%=topic.id.to_s%>)">
                <i><%= bootstrap_icon "x-lg", width: 13, height: 10%></i>
            </button>
        </div>

        <script>
            function myFunctionCloseTopic(id) {
                var x = document.getElementById(id);
                x.style.display = "none";
            }
        </script>
        
        <div class='topic_index_info'>
            <div class='topic_index_name'>
                <a><%= link_to (truncate(strip_tags(topic.name), length: 50)), topic_path(topic) %></a>
            </div>
            <div class='topic_index_count'>
                <a><%= topic.posts.count %> bài viết</a><span> · </span>
                <a><%= topic.topic_follows.count %> người theo dõi</a>
            </div>
        </div>

        <div class='topic_index_description'>
            <a><%= truncate(strip_tags(topic.description), length: 100)%></a>
        </div>

        <div class="topic_index_follow_block" id="topic_follow_<%=topic.id%>">
            <%if user_signed_in?%>
                <% pre_follow = topic.topic_follows.find { |follow| follow.user_id == current_user.id} %>
                <% if pre_follow %>  
                    <%= button_to topic_topic_follow_path(topic, pre_follow, type_param: 'index'), method: :delete, remote: true , form_class: "btn_highlight" do%>
                        <a>Đang theo dõi</a>
                    <%end%> 
                <%else%>
                    <%= button_to topic_topic_follows_path(topic, type_param: 'index'), method: :topic, remote: true, form_class: "btn_normal" do%>
                        <a>Theo dõi</a>
                    <%end%> 
                <%end%>
            <%else%>
                <button type="button" class="btn_normal" data-toggle="modal" data-target="#buttonModalLoginCenter">
                    <a>Theo dõi</a>
                </button>
            <%end%>
        </div>
    </div>
<%end%>

app/views/topics/index.html.erb
<% content_for :meta_robots, "all" %>
<% content_for :meta_title, "Các chủ đề hot, thịnh hành, được nhiều người quan tâm" %>

<div class='topic_index_container'>
	<div class='container'>
		<div class='topic_index_new'>
			<%= button_to new_topic_path, method: :get do%>
                Thêm topic mới
            <%end%>
		</div>
		<div class='row'>
		    <%@topics.each do |topic|%>
				<div class='col-sm-3 col-nopadding'>
					<%= render :partial => 'topics/topic', :locals => {:mini_tyle => false}, :object => topic %>
		    	</div>
		    <%end%>
			<div id="paginate">
				<%= paginate @topics, window: 1, outer_window: 1%>
			</div>
		</div>
	</div>
</div>

app/views/topics/new.html.erb
<% content_for :meta_title, "Tạo chủ đề mới" %>
<%= render 'form', topic: @topic %>

app/views/topics/show.html.erb
<% content_for :meta_robots, "all" %>
<% content_for :meta_title, @topic.name %>
<%if @topic.description%>
	<% content_for :meta_description, @topic.description %>
<%end%>

<div class="topic_show_container">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-nopadding">
                <div class='topic_show_info'>
                    <%if @topic.cover_image?%>
                        <div class='topic_show_info_cover'>
                            <%= image_tag(@topic.cover_image.url)%>
                        </div>
                    <%else%>
                        <div class='topic_show_info_cover'>
                            <%= image_tag("default-cover.jpg")%>
                        </div>
                    <%end%>

                    <%if @topic.avatar?%>
                        <div class='topic_show_info_avatar'>
                            <%= image_tag(@topic.avatar.url)%>
                        </div>
                    <%else%>
                        <div class='topic_show_info_avatar'>
                            <%= image_tag("default-avartar.jpg")%>
                        </div>
                    <%end%>

                    <div class='topic_show_info_data'>
                        <div class='topic_show_info_title'>
                            <a><%=@topic.name%></a>
                        </div>
                        <div class='topic_show_info_count'>
                            <a><%= @topic.posts.count %> bài viết</a><span> · </span>
                            <a><%= @topic.topic_follows.count %> người theo dõi</a>
                        </div>
                        <div class='topic_show_info_des'>
                            <a><%=@topic.description%></a>
                        </div>
                    </div>

                    <div class="topic_show_action_block">
                        <div class="topic_show_follow_block" id="topic_follow_<%=@topic.id%>">
                            <%if user_signed_in?%>
                                <% pre_follow = @topic.topic_follows.find { |follow| follow.user_id == current_user.id} %>
                                <% if pre_follow %>  
                                    <%= button_to topic_topic_follow_path(@topic, pre_follow), method: :delete, remote: true , form_class: "btn_highlight" do%>
                                        <a>Đang theo dõi</a>
                                    <%end%> 
                                <%else%>
                                    <%= button_to topic_topic_follows_path(@topic), method: :topic, remote: true, form_class: "btn_normal" do%>
                                        <a>Theo dõi</a>
                                    <%end%> 
                                <%end%>
                            <%else%>
                                <button type="button" class="btn_normal" data-toggle="modal" data-target="#buttonModalLoginCenter">
                                    <a>Theo dõi</a>
                                </button>
                            <%end%>
                        </div>

                        <div class='topic_show_info_action'>
                            <button class="topic_show_option_btn" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i><%= bootstrap_icon "three-dots-vertical", width: 18, height: 18%></i>
                            </button>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                                <div class="dropdown-item">
                                    <%if user_signed_in?%>
                                        <button type="button" class="btn" data-toggle="modal" data-target="#buttonModalCenter">
                                            Báo xấu
                                        </button>
                                    <%else%>
                                        <button type="button" class="btn" data-toggle="modal" data-target="#buttonModalLoginCenter">
                                            Báo xấu
                                        </button>
                                    <%end%>
                                </div>
                            </div>
                            <!-- Modal -->
                            <div class="modal fade" id="buttonModalCenter" tabindex="-1" role="dialog" aria-hidden="true">
                                <div class="modal-dialog modal-dialog-centered" role="document">
                                    <div class="modal-content">
                                        <%= render :partial => 'topic_reports/form', object: @topic %>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-8 col-nopadding">
                <%if @topic.posts.count > 0%>
                    <div class='topic_show_middle'>
                        <div class="topic_show_post_sort">
                            <div class="topic_show_post_tab_link">
                                <ul class="nav">
                                    <li class="nav-item">
                                        <%if @tab_id == "default" || @tab_id == "TopicPostForYou"%>
                                            <%active = "active"%>
                                        <%else%> 
                                            <%active = ""%>
                                        <%end%>
                                        <a class="nav-link <%=active%>" href="<%=topic_path(@topic, tab_id: 'TopicPostForYou')%>"><i><%= bootstrap_icon "megaphone", width: 18, height: 18%></i>For U </a>
                                    </li>
                                    <li class="nav-item">
                                        <%if @tab_id == "TopicPostTrendID"%>
                                            <%active = "active"%>
                                        <%else%> 
                                            <%active = ""%>
                                        <%end%>
                                        <a class="nav-link <%=active%>" href="<%=topic_path(@topic, tab_id: 'TopicPostTrendID')%>"><i><%= bootstrap_icon "arrow-up-right-square", width: 18, height: 18%></i>Trending </a>
                                    </li>
                                    <li class="nav-item">
                                        <%if @tab_id == "TopicPostNewID"%>
                                            <%active = "active"%>
                                        <%else%> 
                                            <%active = ""%>
                                        <%end%>
                                        <a class="nav-link <%=active%>" href="<%=topic_path(@topic, tab_id: 'TopicPostNewID')%>"><i><%= bootstrap_icon "lightning", width: 18, height: 18%></i>Mới nhất </a>
                                    </li>
                                    <li class="nav-item">
                                        <%if @tab_id == "TopicPostTopID"%>
                                            <%active = "active"%>
                                        <%else%> 
                                            <%active = ""%>
                                        <%end%>
                                        <a class="nav-link <%=active%>" href="<%=topic_path(@topic, tab_id: 'TopicPostTopID')%>"><i><%= bootstrap_icon "shift", width: 19, height: 19%></i>Top </a>
                                    </li>
                                    <%if @tab_id == "TopicPostTopID" || @tab_id == "TopicPostTopWeekID" || @tab_id == "TopicPostTopMonthID" || @tab_id == "TopicPostTopYearID"%>
                                        <li class="nav-item">
                                            <%if @tab_id == "TopicPostTopWeekID"%>
                                                <%active = "active"%>
                                            <%else%> 
                                                <%active = ""%>
                                            <%end%>
                                            <a class="nav-link <%=active%>" href="<%=topic_path(@topic, tab_id: 'TopicPostTopWeekID')%>">Top tuần</a>
                                        </li>
                                        <li class="nav-item">
                                            <%if @tab_id == "TopicPostTopMonthID"%>
                                                <%active = "active"%>
                                            <%else%> 
                                                <%active = ""%>
                                            <%end%>
                                            <a class="nav-link <%=active%>" href="<%=topic_path(@topic, tab_id: 'TopicPostTopMonthID')%>">Top tháng</a>
                                        </li>
                                        <li class="nav-item">
                                            <%if @tab_id == "TopicPostTopYearID"%>
                                                <%active = "active"%>
                                            <%else%> 
                                                <%active = ""%>
                                            <%end%>
                                            <a class="nav-link <%=active%>" href="<%=topic_path(@topic, tab_id: 'TopicPostTopYearID')%>">Top năm</a>
                                        </li>
                                    <%end%>
                                    <li class="nav-item">
                                        <%if @tab_id == "TopicPostPodID"%>
                                            <%active = "active"%>
                                        <%else%> 
                                            <%active = ""%>
                                        <%end%>
                                        <a class="nav-link <%=active%>" href="<%=topic_path(@topic, tab_id: 'TopicPostPodID')%>"><i><%= bootstrap_icon "mic", width: 19, height: 19%></i>Podcasts </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        
                        <div class="topic_show_post_tab_content">
                            <%if @posts.present?%>
                                <div id="topic_show_infinite_scroll">
                                    <%= render @posts %>
                                </div>
                                <%if @posts.total_count > 10%>
                                    <div class="topic_show_pagination_button" id="topic_show_pagination">
                                        <%= link_to_next_page(@posts, 'Xem thêm', :remote => true) %>
                                    </div>
                                <%end%>
                            <%end%>
                        </div>
                    </div>
                <%else%>
                    <div class="topic_show_middle_not_found_block">
                        <div class="topic_show_middle_not_found_icon">
                            <i><%= bootstrap_icon "pencil-square", width: 24, height: 24%></i>
                        </div>
                        <div class="topic_show_middle_not_found">
                            <span>Chưa có bài viết nào, hãy là người đầu tiên viết bài cho chủ đề này</span>
                        </div>
                    </div>
                <%end%>
            </div>
            <div class="col-sm-4 col-nopadding">
                <div class='topic_show_right_top_block'>
                    <div class='topic_show_right_title'>
                        <a>Chủ đề khác tương tự</a>
                    </div>
                    
                    <%@topic_relateds.each do |topic|%>
                        <div class="topic_show_right_content">
                            <%= render :partial => 'topics/topic', :locals => {:mini_tyle => true}, :object => topic %>
                        </div>
                    <%end%>
                    
                    <div class='topic_show_right_all_topic'>
                        <%= button_to categories_path, method: :get, form_class: "topic_show_right_all_topic_button" do%>
                            <a>Xem tất cả(<%=convert_number_to_human(Topic.all.count)%>)</a>
                        <%end%> 
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/topics/show.js.erb
// Append new data
$("<%=j render @posts %>").appendTo($("#topic_show_infinite_scroll"));

// Update pagination link
<% if @posts.last_page? %>
  $('#topic_show_pagination').remove();
<% else %>
  $('#topic_show_pagination').html("<%=j link_to_next_page(@posts, 'Xem thêm', :remote => true) %>");
<% end %>