config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations',
    passwords: 'admins/passwords'
  }

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Ckeditor::Engine => '/ckeditor'

  get 'user_wellcome' => 'users#wellcome'
  
  resources :users do
    resources :user_notifications
    resources :user_follows
  end
  
  resources :posts do
    resources :post_votes
    resources :post_follows
    resources :post_comments
    resources :post_reports
  end

  resources :post_comments do
    resources :post_comment_votes
    resources :post_comment_reports
  end

  resources :categories do
    resources :topics
  end

  resources :topics do
    resources :topic_follows
    resources :topic_reports
  end

  resources :post_comments do
    resources :post_comments
  end

  resources :pages

  resources :scrapers

  get 'page_search' => 'pages#search'
  root "pages#home"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post_follow.rb
class PostFollow < ApplicationRecord
    belongs_to :post, optional: true
end

app/controllers/post_follows_controller.rb
class PostFollowsController < ApplicationController
    before_action :require_login, only: [:new, :create, :edit, :update, :destroy]
    
    def index 
        @post = Post.friendly.find(params[:post_id])
        @post_follows = @post.post_follows
    end

    def new
        @post = Post.friendly.find(params[:post_id])
        @post_follow = PostFollow.new
    end

    def create
        @post = Post.friendly.find(params[:post_id])
        @post_follow = PostFollow.new
        if !already_followed?
            @post_follow = @post.post_follows.build(user_id: current_user.id)
            @post_follow.save!
        end
        @type_param = params[:type_param]

        respond_to do |format|
            format.html {}
            format.js
        end
    end

    def edit
    end

    def update
    end
    
    def destroy
        @post = Post.friendly.find(params[:post_id])
        @post_follow = @post.post_follows.find(params[:id])
        @post_follow.destroy
        @type_param = params[:type_param]

        respond_to do |format|
            format.html {}
            format.js
        end
    end

    def show
    end

    private

    def already_followed?
        PostFollow.where(user_id: current_user.id, post_id: params[:post_id]).exists?
    end
end

app/helpers/post_follows_helper.rb
module PostFollowsHelper
end

app/views/post_follows/_follow.html.erb
<%if @type_param == "index" %>
    <div id="post_follow_<%=@post.id%>">
        <%if user_signed_in?%>
            <% pre_follow = @post.post_follows.find { |follow| follow.user_id == current_user.id} %>
        <%end%>
        <% if pre_follow %>  
            <%= button_to post_post_follow_path(@post, pre_follow, type_param: 'index'), method: :delete, remote: true, form_class: "btn_highlight" do%>
                <i><%= bootstrap_icon "save2-fill", width: 16, height: 16%></i>
            <%end%> 
        <%else%>
            <%= button_to post_post_follows_path(@post, type_param: 'index'), method: :post, remote: true, form_class: "btn_normal" do%>
                <i><%= bootstrap_icon "save2", width: 16, height: 16%></i>
            <%end%> 
        <%end%>
    </div>
<%else%>
    <%if user_signed_in?%>
        <% pre_follow = @post.post_follows.find { |follow| follow.user_id == current_user.id} %>
    <%end%>
    <% if pre_follow %>  
        <%= button_to post_post_follow_path(@post, pre_follow), method: :delete, remote: true, form_class: "btn_highlight" do%>
            <i><%= bootstrap_icon "save2-fill", width: 17, height: 17%></i>
        <%end%> 
    <%else%>
        <%= button_to post_post_follows_path(@post), method: :post, remote: true, form_class: "btn_normal" do%>
            <i><%= bootstrap_icon "save2", width: 17, height: 17%></i>
        <%end%> 
    <%end%>
<%end%>

app/views/post_follows/create.js.erb
$('#post_follow_<%=@post.id%>').html('<%= j render partial: "post_follows/follow", locals: {post: @post} %>');

app/views/post_follows/destroy.js.erb
$('#post_follow_<%=@post.id%>').html('<%= j render partial: "post_follows/follow", locals: {post: @post} %>');