config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations',
    passwords: 'admins/passwords'
  }

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Ckeditor::Engine => '/ckeditor'

  get 'user_wellcome' => 'users#wellcome'
  
  resources :users do
    resources :user_notifications
    resources :user_follows
  end
  
  resources :posts do
    resources :post_votes
    resources :post_follows
    resources :post_comments
    resources :post_reports
  end

  resources :post_comments do
    resources :post_comment_votes
    resources :post_comment_reports
  end

  resources :categories do
    resources :topics
  end

  resources :topics do
    resources :topic_follows
    resources :topic_reports
  end

  resources :post_comments do
    resources :post_comments
  end

  resources :pages

  resources :scrapers

  get 'page_search' => 'pages#search'
  root "pages#home"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    # You should configure your model like this:
	# devise :users, omniauth_providers: [:google]
	before_action :save_my_previous_url, only: [:new]
	skip_before_action :verify_authenticity_token, only: :facebook

	def google_oauth2
		@user = User.from_omniauth(request.env["omniauth.auth"])

		if @user.persisted?
		flash[:success] = t 'devise.omniauth_callbacks.success', kind: 'Google'
		sign_in_and_redirect @user, event: :authentication
		else
		# session["devise.omniauth_callbacks"] = request.env["omniauth.auth"].except(:extra) # Removing extra as it can overflow some session stores
		redirect_to new_user_session_url
		end
	end

	def facebook
		# You need to implement the method below in your model (e.g. app/models/user.rb)
		@user = User.from_omniauth(request.env["omniauth.auth"])

		if @user.persisted?
		flash[:success] = t 'devise.omniauth_callbacks.success', kind: 'Facebook'
		sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
		else
		# session["devise.facebook_data"] = request.env["omniauth.auth"].except(:extra) # Removing extra as it can overflow some session stores
		redirect_to new_user_session_url
		end
	end

	def failure 
		redirect_to root_path 
	end 

	# You should also create an action method in this controller like this:
	# def twitter
	# end

	# More info at:
	# https://github.com/heartcombo/devise#omniauth

	# GET|POST /resource/auth/twitter
	# def passthru
	#   super
	# end

	# GET|POST /users/auth/twitter/callback
	# def failure
	#   super
	# end

	protected

	# The path used when OmniAuth fails
	def after_omniauth_failure_path_for(_scope)
		new_users_session_path
	end
	
	# The path used after sign in.
	def after_sign_in_path_for(resource_or_scope)
        if (session[:my_previous_url].to_s == new_user_session_path || 
            session[:my_previous_url].to_s == user_session_path || 
            session[:my_previous_url].to_s == destroy_user_session_path || 
            session[:my_previous_url].to_s == user_facebook_omniauth_authorize_path || 
            session[:my_previous_url].to_s == user_facebook_omniauth_callback_path || 
            session[:my_previous_url].to_s == user_google_oauth2_omniauth_authorize_path || 
            session[:my_previous_url].to_s == user_google_oauth2_omniauth_callback_path || 
            session[:my_previous_url].to_s == new_user_password_path || 
            session[:my_previous_url].to_s == edit_user_password_path || 
            session[:my_previous_url].to_s == user_password_path || 
            session[:my_previous_url].to_s == cancel_user_registration_path || 
            session[:my_previous_url].to_s == new_user_registration_path || 
            session[:my_previous_url].to_s == edit_user_registration_path || 
            session[:my_previous_url].to_s == user_registration_path || 
            session[:my_previous_url].to_s == users_path || 
            session[:my_previous_url].to_s == new_user_path || 
            session[:my_previous_url].to_s == edit_user_path(current_user) || 
            session[:my_previous_url].to_s == user_path(current_user))
            
            session[:my_previous_url] = root_path
        end

		# Show wellcome path
        if current_user.sign_in_count == 0
            session[:my_previous_url] = user_wellcome_path
        end

        stored_location_for(resource_or_scope) || session[:my_previous_url]
    end

	def save_my_previous_url
        session[:my_previous_url] = URI(request.referer || '').path
    end

end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
    # before_action :configure_sign_up_params, only: [:create]
    # before_action :configure_account_update_params, only: [:update]
    before_action :configure_permitted_parameters, if: :devise_controller?

    # GET /resource/sign_up
    # def new
    #   super
    # end

    # POST /resource
    # def create
    #   super
    # end

    # GET /resource/edit
    # def edit
    #   super
    # end

    # PUT /resource
    # def update
    #   super
    # end

    # DELETE /resource
    # def destroy
    #   super
    # end

    # GET /resource/cancel
    # Forces the session data which is usually expired after sign
    # in to be expired now. This is useful if the user wants to
    # cancel oauth signing in/up in the middle of the process,
    # removing all OAuth session data.
    # def cancel
    #   super
    # end

    # protected

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_up_params
    #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
    # end

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_account_update_params
    #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
    # end

    # The path used after sign up.
    def after_sign_up_path_for(resource_or_scope)
        # Show wellcome path
        stored_location_for(resource_or_scope) || user_wellcome_path
    end

    # The path used after sign up for inactive accounts.
    # def after_inactive_sign_up_path_for(resource)
    #   super(resource)
    # end

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up) { |u|
            u.permit(:name, :email, :password, :password_confirmation)
        }
    end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
    before_action :save_my_previous_url, only: [:new]
    # before_action :configure_sign_in_params, only: [:create]

    # GET /resource/sign_in
    # def new
    #   super
    # end

    # POST /resource/sign_in
    # def create
    #   super
    # end

    # DELETE /resource/sign_out
    # def destroy
    #   super
    # end

    # protected

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_in_params
    #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
    # end

    # The path used after sign in.
    def after_sign_in_path_for(resource_or_scope)
        if (session[:my_previous_url].to_s == new_user_session_path || 
            session[:my_previous_url].to_s == user_session_path || 
            session[:my_previous_url].to_s == destroy_user_session_path || 
            session[:my_previous_url].to_s == user_facebook_omniauth_authorize_path || 
            session[:my_previous_url].to_s == user_facebook_omniauth_callback_path || 
            session[:my_previous_url].to_s == user_google_oauth2_omniauth_authorize_path || 
            session[:my_previous_url].to_s == user_google_oauth2_omniauth_callback_path || 
            session[:my_previous_url].to_s == new_user_password_path || 
            session[:my_previous_url].to_s == edit_user_password_path || 
            session[:my_previous_url].to_s == user_password_path || 
            session[:my_previous_url].to_s == cancel_user_registration_path || 
            session[:my_previous_url].to_s == new_user_registration_path || 
            session[:my_previous_url].to_s == edit_user_registration_path || 
            session[:my_previous_url].to_s == user_registration_path || 
            session[:my_previous_url].to_s == users_path || 
            session[:my_previous_url].to_s == new_user_path || 
            session[:my_previous_url].to_s == edit_user_path(current_user) || 
            session[:my_previous_url].to_s == user_path(current_user))
            
            session[:my_previous_url] = root_path
        end

        # Show wellcome path
        if current_user.sign_in_count == 0
            session[:my_previous_url] = user_wellcome_path
        end

        stored_location_for(resource_or_scope) || session[:my_previous_url]
    end

    def save_my_previous_url
        session[:my_previous_url] = URI(request.referer || '').path
    end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    include UsersHelper
    include TopicsHelper
    before_action :require_login, only: [:index, :edit, :update, :destroy]
    
    def index
        @users = User.all
    end

    def new
        @user = User.new
    end
    
    def create
        @user = User.new(user_params)
    end

    def show
        @user = User.friendly.find params[:id]
        @topics = Topic.all.sort_by{|topic| cal_topic_trend_point(topic)}.reverse.first(10)
        if(params.has_key?(:tab_id))
            @tab_id = params[:tab_id]
        else
            @tab_id = "default"
        end
        
        if "default" == @tab_id || "UserPostID" == @tab_id
            @buffers = find_owner_post_for_user(@user)
            @user_posts = Kaminari.paginate_array(@buffers).page(params[:page]).per(10)
        end
    
        if "UserTopicID" == @tab_id
            @buffers = find_owner_topic_for_user(@user)
            @user_topics = Kaminari.paginate_array(@buffers).page(params[:page]).per(10)
        end
    
        if "UserTopicFollowID" == @tab_id
            @buffers = find_owner_topic_follow_for_user(@user)
            @user_topic_follows = Kaminari.paginate_array(@buffers).page(params[:page]).per(10)
        end
    
        if "UserCommentID" == @tab_id
            @buffers = find_owner_post_comment_for_user(@user)
            @user_comments = Kaminari.paginate_array(@buffers).page(params[:page]).per(10)
        end
    
        if "UserUpvoteID" == @tab_id
            @buffers = find_owner_post_upvote_for_user(@user)
            @user_upvotes = Kaminari.paginate_array(@buffers).page(params[:page]).per(10)
        end
    
        if "UserDownvoteID" == @tab_id
            @buffers = find_owner_post_downvote_for_user(@user)
            @user_downvotes = Kaminari.paginate_array(@buffers).page(params[:page]).per(10)
        end
    
        if "UserSaveID" == @tab_id
            @buffers = find_owner_post_save_for_user(@user)
            @user_saves = Kaminari.paginate_array(@buffers).page(params[:page]).per(10)
        end
    
        if "UserNotificationID" == @tab_id
            @buffers = @user.user_notifications
            @user_notifications = Kaminari.paginate_array(@buffers).page(params[:page]).per(10)
        end

        if "UserFollowingID" == @tab_id
            @buffers = @user.followers
            @user_followers = Kaminari.paginate_array(@buffers).page(params[:page]).per(10)
        end

        if "UserFollowedID" == @tab_id
            @buffers = @user.followees
            @user_followees = Kaminari.paginate_array(@buffers).page(params[:page]).per(10)
        end
    end

    def edit
        @user = User.friendly.find params[:id]
        
        if(params.has_key?(:tab_id))
            @tab_id = params[:tab_id]
        else
            @tab_id = "default"
        end
    end

    def destroy
        @user = User.friendly.find params[:id]
        @user.destroy
        redirect_to root_path
    end

    def update
        @user = User.friendly.find params[:id]
        @user.update_without_password(user_params)
        redirect_to edit_user_path(@user)
    end

    def try(arg)
        self[arg] rescue nil
    end

    def wellcome
        @topics = Topic.all
        @categories = Category.all
    end

private
    def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar, :phone,:address, 
                                    :sign, :education,:job, :site, :birth_day, :company, :school, :introduce, :cover_image,
                                    :noti_when_message, :noti_when_tagging, :noti_when_follow, :noti_when_vote,
                                    :noti_when_unvote, :noti_when_report, :noti_weekly)
    end
end

app/helpers/users_helper.rb
module UsersHelper
    def find_owner_post_for_user(user)
        @owner_posts = Post.first
        if user.id.present?
            @owner_posts = Post.where(user_id: user.id)
        end
        return @owner_posts
    end

    def find_owner_topic_for_user(user)
        @owner_topics = Topic.first
        if user.id.present?
            @owner_topics = Topic.where(user_id: user.id)
        end
        return @owner_topics
    end

    def find_owner_topic_follow_for_user(user)
        @user_owner_topics = []
        if user.id.present?
            @owner_topic_follows = TopicFollow.where(user_id: user.id)
            @owner_topic_follows.each do |topic_follow|
                @user_owner_topics.push(topic_follow.topic)
            end

            @owner_topics = Topic.where(user_id: user.id)
            @owner_topics.each do |topic|
                @user_owner_topics.push(topic)
            end
        end
        return @user_owner_topics
    end

    def find_owner_post_comment_for_user(user)
        @owner_posts = []
        if user.id.present?
            @owner_post_comments = PostComment.where(user_id: user.id, commentable_type: "Post")
            @owner_post_comments.each do |post_comment|
                @owner_posts.push(post_comment.commentable)
            end
        end
        return @owner_posts
    end

    def find_owner_post_upvote_for_user(user)
        @owner_posts = []
        if user.id.present?
            @owner_post_upvotes = PostVote.where(user_id: user.id, vote_type: 1)
            @owner_post_upvotes.each do |post_upvote|
                @owner_posts.push(post_upvote.post)
            end
        end
        return @owner_posts
    end

    def find_owner_post_downvote_for_user(user)
        @owner_posts = []
        if user.id.present?
            @owner_post_downvotes = PostVote.where(user_id: user.id, vote_type: 0)
            @owner_post_downvotes.each do |post_downvote|
                @owner_posts.push(post_downvote.post)
            end
        end
        return @owner_posts
    end

    def find_owner_post_save_for_user(user)
        @owner_posts = []
        if user.id.present?
            @owner_post_saves = PostFollow.where(user_id: user.id)
            @owner_post_saves.each do |post_save|
                @owner_posts.push(post_save.post)
            end
        end
        return @owner_posts
    end
end

app/views/users/_form_setting.html.erb
<% content_for :meta_title, "Cài đặt tài khoản" %>

<div class='user_setting_dasboard'>
	<div class="container">
    	<div class="row">
			<div class="col-sm-8 col-nopadding">
		        <div class='user_setting_title'>
		            <a>Cài đặt thông tin cá nhân cho @<%=current_user.name%></a>
		        </div>

		        <div class="user_setting_tab_link">
		            <ul class="nav">
		                <li class="nav-item">
		                    <%if @tab_id == "default" || @tab_id == "UserSettingPersonalID"%>
		                        <%active = "active"%>
		                    <%else%> 
		                        <%active = ""%>
		                    <%end%>                                 
		                    <a class="nav-link <%=active%>" href="<%=edit_user_path(current_user, tab_id: 'UserSettingPersonalID')%>"><i><%= bootstrap_icon "person", width: 24, height: 24%></i>Thông tin cá nhân</a>
		                </li>
		                <li class="nav-item">
		                    <%if @tab_id == "UserSettingNotiID"%>
		                        <%active = "active"%>
		                    <%else%> 
		                        <%active = ""%>
		                    <%end%>                                     
		                    <a class="nav-link <%=active%>" href="<%=edit_user_path(current_user, tab_id: 'UserSettingNotiID')%>"><i><%= bootstrap_icon "bell", width: 20, height: 20%></i>Thông báo</a>
		                </li>
		            </ul>
		        </div>
		    </div>
		</div>	
		
		<div class="row">
			<div class="col-sm-8 col-nopadding">
				<div class="user_setting_tab_content">
					<%if @tab_id == "default" || @tab_id == "UserSettingPersonalID"%>
						<div class="user_setting_personal_tab">
							<%= form_for @user, html: {class: "form-horizontal"} do |f| %>
								<div class="user_setting_form">
									<div class="user_setting_section">
										<div class="user_setting_description">
											<a>Thông tin cá nhân</a>
										</div>
										<div class="user_setting_content">
											<div class="user_setting_label">
												<a><%= f.label :name, "Tên đăng nhập", class: "user_setting_label_name" %></a>
											</div>

											<div class="user_setting_input">
												<%= f.text_field :name, class: "form-control", placeholder: "Thay đổi tên đăng nhập" %>
											</div>
										</div>

										<div class="user_setting_content">
											<div class="user_setting_label">
												<a><%= f.label :email, "Địa chỉ email", class: "user_setting_label_name" %></a>
											</div>

											<div class="user_setting_input">
												<%= f.text_field :email, class: "form-control", placeholder: "Thay đổi địa chỉ email" %>
											</div>
										</div>

										<div class="user_setting_content">
											<div class="user_setting_label">
												<a><%= f.label :introduce, "Mô tả về bản thân", class: "user_setting_label_name" %></a>
											</div>

											<div class="user_setting_input">
												<%= f.text_area :introduce, class: "form-control-rich-text", placeholder: "Mô tả ngắn vê bản thân" %>
											</div>
										</div>

										<div class="user_setting_content">
											<div class="user_setting_label">
												<a><%= f.label :avatar, "Ảnh đại diện", class: "user_setting_label_name" %></a>
											</div>

											<div class="user_setting_input">
												<%= f.file_field :avatar, class: "form-control", placeholder: "Thay đổi ảnh đại diện" %>
											</div>
										</div>

										<div class="user_setting_content">
											<div class="user_setting_label">
												<a><%= f.label :cover_image, "Ảnh bìa", class: "user_setting_label_name" %></a>
											</div>

											<div class="user_setting_input">
												<%= f.file_field :cover_image, class: "form-control", placeholder: "Thay đổi ảnh bìa" %>
											</div>
										</div>
									</div>
									
									<div class="user_setting_section">
										<div class="user_setting_description">
											<a>Thông tin khác</a>
										</div>

										<div class="user_setting_content">
											<div class="user_setting_label">
												<a><%= f.label :birth_day, "Ngày sinh", class: "user_setting_label_name" %></a>
											</div>

											<div class="user_setting_input">
												<%= f.date_field :birth_day, class: "form-control", placeholder: "Thay đổi ngày sinh" %>
											</div>
										</div>

										<div class="user_setting_content">
											<div class="user_setting_label">
												<a><%= f.label :phone, "Số điện thoại", class: "user_setting_label_name" %></a>
											</div>

											<div class="user_setting_input">
												<%= f.text_field :phone, class: "form-control", placeholder: "Thay đổi số điện thoại" %>
											</div>
										</div>

										<div class="user_setting_content">
											<div class="user_setting_label">
												<a><%= f.label :address, "Địa chỉ", class: "user_setting_label_name" %></a>
											</div>

											<div class="user_setting_input">
												<%= f.text_field :address, class: "form-control", placeholder: "Thay đổi địa chỉ" %>
											</div>
										</div>
									</div>

									<div class="user_setting_section">
										<div class="user_setting_description">
											<a>Việc làm</a>
										</div>

										<div class="user_setting_content">
											<div class="user_setting_label">
												<a><%= f.label :job, "Công việc hiện tai", class: "user_setting_label_name" %></a>
											</div>

											<div class="user_setting_input">
												<%= f.text_field :job, class: "form-control", placeholder: "Thay đổi việc làm" %>
											</div>
										</div>

										<div class="user_setting_content">
											<div class="user_setting_label">
												<a><%= f.label :company, "Công ty", class: "user_setting_label_name" %></a>
											</div>

											<div class="user_setting_input">
												<%= f.text_field :company, class: "form-control", placeholder: "Thay đổi công ty" %>
											</div>
										</div>

										<div class="user_setting_content">
											<div class="user_setting_label">
												<a><%= f.label :education, "Học vấn", class: "user_setting_label_name" %></a>
											</div>

											<div class="user_setting_input">
												<%= f.text_field :education, class: "form-control", placeholder: "Thay đổi học vấn" %>
											</div>
										</div>

										<div class="user_setting_content">
											<div class="user_setting_label">
												<a><%= f.label :school, "Trường học", class: "user_setting_label_name" %></a>
											</div>

											<div class="user_setting_input">
												<%= f.text_field :school, class: "form-control", placeholder: "Thay đổi trường học" %>
											</div>
										</div>
									</div>

									<div class="user_setting_section">
										<div class="user_setting_description">
											<a>Mục khác</a>
										</div>

										<div class="user_setting_content">
											<div class="user_setting_label">
												<a><%= f.label :sign, "Chữ kí", class: "user_setting_label_name" %></a>
											</div>

											<div class="user_setting_input">
												<%= f.text_area :sign, class: "form-control-rich-text", placeholder: "Thêm chữ kí của bạn" %>
											</div>
										</div>
									</div>
									
									<div class="user_setting_submit">
										<%= f.submit "Lưu thay đổi", class: "user_setting_form_submit" %>
									</div>
								</div>
							<%end%>
						</div>
					<%end%>

					<%if @tab_id == "UserSettingNotiID"%>
						<div class="user_setting_noti_tab">
							<div class="user_setting_form">
								<%= simple_form_for @user, html: {class: "form-horizontal"} do |f| %>
									<div class="user_setting_section">
										<div class="user_setting_label">
											<a>Cài đặt thông báo</a>
										</div>
										<div class="user_setting_content">
											<div class="user_setting_check_box">
												<span><%= f.input_field :noti_when_message, as: :boolean %></span>
												<a><%= f.label :noti_when_message, "Gửi thông báo khi có tin nhắn", class: "user_setting_label_name" %></a>
											</div>
											<div class="user_setting_check_box">
												<span><%= f.input_field :noti_when_comment, as: :boolean %></span>
												<a><%= f.label :noti_when_comment, "Gửi thông báo khi ai đó bình luận nội dung của tôi", class: "user_setting_label_name" %></a>
											</div>
											<div class="user_setting_check_box">
												<span><%= f.input_field :noti_when_tagging, as: :boolean %></span>
												<a><%= f.label :noti_when_tagging, "Gửi thông báo khi ai đó nhắc tới tôi", class: "user_setting_label_name" %></a>
											</div>
											<div class="user_setting_check_box">
												<span><%= f.input_field :noti_when_follow, as: :boolean %></span>
												<a><%= f.label :noti_when_follow, "Gửi thông báo khi ai đó theo dõi tôi", class: "user_setting_label_name" %></a>
											</div>
											<div class="user_setting_check_box">
												<span><%= f.input_field :noti_when_vote, as: :boolean %></span>
												<a><%= f.label :noti_when_vote, "Gửi thông báo khi ai đó bình chọn cho bài đăng của tôi", class: "user_setting_label_name" %></a>
											</div>
											<div class="user_setting_check_box">
												<span><%= f.input_field :noti_when_unvote, as: :boolean %></span>
												<a><%= f.label :noti_when_unvote, "Gửi thông báo khi ai đó không bình chọn cho bài đăng của tôi", class: "user_setting_label_name" %></a>
											</div>
											<div class="user_setting_check_box">
												<span><%= f.input_field :noti_when_report, as: :boolean %></span>
												<a><%= f.label :noti_when_report, "Gửi thông báo khi ai đó report bài đăng của tôi", class: "user_setting_label_name" %></a>
											</div>
											<div class="user_setting_check_box">
												<span><%= f.input_field :noti_weekly, as: :boolean %></span>
												<a><%= f.label :noti_weekly, "Gửi cho tôi những bài đăng gợi ý về chủ để tôi quan tâm", class: "user_setting_label_name" %></a>
											</div>
										</div>
									</div>

									<div class="user_setting_submit">
										<%= f.submit "Lưu thay đổi", class: "user_setting_form_submit" %>
									</div>
								<%end%>
							</div>
						</div>
					<%end%>
				</div>
			</div>
		</div>
    </div>
</div>

app/views/users/_user.html.erb
<div class='user_index_block'>
    <%if user.avatar?%>
        <div class='user_index_avatar'>
            <%= link_to (image_tag(user.avatar.url)), image_path(url_for(user.avatar.url)), rel: "gallery" , :href => user_path(user)%>
        </div>
    <%else%>
        <div class="user_index_avatar">
            <%= link_to (image_tag("default-user.png")), image_path(url_for("default-user.png")), rel: "gallery" , :href => user_path(user)%>
        </div>		
    <%end%>
    <div class='user_index_name'>
        <a><%= link_to (user.name), user_path(user) %></a>
        <%if user.official%>
            <i><%= bootstrap_icon "check-circle-fill", width: 14, height: 14, fill: '#5865f2'%></i>
        <%end%>
    </div>

    <div class='user_index_nickname'>
        <a>@<%= user.name.downcase%></a>
    </div>

    <%if user_signed_in?%>
        <%if current_user.id != user.id%>
            <div class="user_index_follow" id="user_follow_<%=user.id%>">
                <% pre_follow = user.followed_users.find { |follow| follow.followee_id == current_user.id} %>
                <% if pre_follow %>  
                    <%= button_to user_user_follow_path(user, pre_follow, type_param: "index"), method: :delete, remote: true, form_class: "btn_highlight" do%>
                        <a>Đang theo dõi</a>
                    <%end%> 
                <%else%>
                    <%= button_to user_user_follows_path(user, type_param: "index"), method: :post, remote: true, form_class: "btn_normal" do%>
                        <a>Theo dõi</a>
                    <%end%>
                <%end%>
            </div>
        <%end%>
    <%else%>
        <div class="user_index_follow">
            <button type="button" class="btn_normal" data-toggle="modal" data-target="#buttonModalLoginCenter">
                <a>Theo dõi</a>
            </button>
        </div>
    <%end%>
</div>

app/views/users/edit.html.erb
<%- model_class = User -%>
<%= render :partial => 'users/form_setting' %>

app/views/users/wellcome.html.erb
<% content_for :meta_title, "Chào mừng !!!" %>

<div class='wellcome_user_index_container'>
	<div class='container'>
		<div class='wellcome_user_index_label'>
			<a>Wellcome, <span><%= link_to (current_user.name), user_path(current_user) %></span> hãy theo dõi ít nhất 5 chủ đề mà bạn yêu thích</a>
		</div>
		<div class='wellcome_user_index_content'>
			<%@categories.each do |category|%>
				<div class='wellcome_user_index_render'>
					<%= render category%>
				</div>
			<%end%>
		</div>

		<div class='wellcome_user_index_next'>
			<%= button_to root_path, method: :get do%>
                <a>Tiếp theo <i><%= bootstrap_icon "arrow-right-short", width: 18, height: 18%></i></a>
            <%end%> 
		</div>
	</div>
</div>