config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations',
    passwords: 'admins/passwords'
  }

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Ckeditor::Engine => '/ckeditor'

  get 'user_wellcome' => 'users#wellcome'
  
  resources :users do
    resources :user_notifications
    resources :user_follows
  end
  
  resources :posts do
    resources :post_votes
    resources :post_follows
    resources :post_comments
    resources :post_reports
  end

  resources :post_comments do
    resources :post_comment_votes
    resources :post_comment_reports
  end

  resources :categories do
    resources :topics
  end

  resources :topics do
    resources :topic_follows
    resources :topic_reports
  end

  resources :post_comments do
    resources :post_comments
  end

  resources :pages

  resources :scrapers

  get 'page_search' => 'pages#search'
  root "pages#home"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
    extend FriendlyId
    def convert_slug
        slug = title.downcase.to_s
        slug.gsub! /[àáạãảâậấẫầẩăặắằẵẳ]/, "a"
        slug.gsub! /[đ]/, "d"
        slug.gsub! /[èéẹẽẻêềếệễể]/, "e"
        slug.gsub! /[óòọõỏôốồộỗổơớợỡờở]/, "o"
        slug.gsub! /[úùụũủưứựừữử]/, "u"
        slug.gsub! /[íịìĩỉ]/, "i"
        slug.gsub! /[ýỵỹỳỷ]/, "y"
        return slug
    end
    friendly_id :convert_slug, use: :slugged

    has_many :post_votes, dependent: :destroy
    has_many :post_follows, dependent: :destroy
    has_many :post_reports, dependent: :destroy
    has_many :post_comments, as: :commentable

    has_many :post_images
    accepts_nested_attributes_for :post_images

    has_many :post_links

    has_many :topings
    has_many :topics, through: :topings

    has_rich_text :content_rich_text

    mount_uploader :podcast, FileUploader

    def self.topicged_with(name)
        Topic.find_by!(name: name).posts
    end

    def self.topic_counts
        Topic.select('topics.*, count(topings.topic_id) as count').joins(:topings).group('topings.topic_id')
    end

    def topic_list
        topics.map(&:name).join(', ')
    end

    def topic_list=(names)
        self.topics = names.split(',').map do |n|
            Topic.where(name: n.strip).first_or_create!
        end
    end

    def self.search(search)
        if search
            target_search = Post.where("title ILIKE?", "%#{search}%")
            if(target_search)
                self.where(id: target_search)
            end
        end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    include PostsHelper
    include PostCommentsHelper
    include UsersHelper
    include ApplicationHelper

    before_action :set_post, only: %i[ show edit update destroy ]
    before_action :require_login, only: [:new, :create, :edit, :update, :destroy]

    # GET /posts or /posts.json
    def index
        @posts = Post.all.page(params[:page]).per(10)
    end

    # GET /posts/1 or /posts/1.json
    def show
        @post = Post.friendly.find(params[:id])
        @post.increment!(:view_count)
        @post_images = @post.post_images.all
        @post_comments = @post.post_comments

		@owner_post_user = find_owner_user(@post)
        @owner_post = find_owner_post_for_user(@owner_post_user)
        @user_post_relateds = @owner_post.reject{|i| i.id == @post.id}
        @user_post_relateds = @user_post_relateds.sort_by{|post| cal_post_top_point(post)}.reverse.first(10)

        # Sort comment
        if(params.has_key?(:tab_id))
            @tab_id = params[:tab_id]
        else
            @tab_id = "default"
        end

        if "default" == @tab_id || "PostCommentBest" == @tab_id
            @buffers = @post.post_comments.sort_by{|post_comment| cal_post_comment_best_point(post_comment)}.reverse
            @post_comments = Kaminari.paginate_array(@buffers).page(params[:page]).per(10)
        end
    
        if "PostCommentNew" == @tab_id
            @buffers = @post.post_comments.order('created_at DESC')
            @post_comments = Kaminari.paginate_array(@buffers).page(params[:page]).per(10)
        end

        if "PostCommentTop" == @tab_id
            @buffers = @post.post_comments.sort_by{|post_comment| cal_post_comment_top_point(post_comment)}.reverse
            @post_comments = Kaminari.paginate_array(@buffers).page(params[:page]).per(10)
        end

        if "PostCommentOld" == @tab_id
            @buffers = @post.post_comments.order('created_at DESC').reverse
            @post_comments = Kaminari.paginate_array(@buffers).page(params[:page]).per(10)
        end

        respond_to do |format|
            format.html {}
            format.js
        end
    end

    # GET /posts/new
    def new
        @post = Post.new
        @post_image = @post.post_images.build
        @post_link = @post.post_links.build

        # handle share
        @post_shared = nil
        if (params.has_key?(:post_shared_id))
            @post_shared = Post.friendly.find(params[:post_shared_id])
        end

        if(params.has_key?(:tab_id))
            @tab_id = params[:tab_id]
        else
            @tab_id = "default"
        end
    end

    # GET /posts/1/edit
    def edit
    end

    # POST /posts or /posts.json
    def create
        @post = Post.new(post_params)
        @post.user_id = current_user.id

        if @post.save
            # save image
            if(params.has_key?(:post_images))
                params[:post_images]['image'].each do |a|
                    @post_image = @post.post_images.create!(:image => a, :post_id => @post.id)
                end
            end
            
            # count number of share
            if @post.post_shared_id.present? && @post.post_shared_id > 0
                @post_shared = Post.friendly.find(@post.post_shared_id)
                @post_shared.increment!(:share_count)
            end

            # save link data
            if(@post.link.present?)
                @link = LinkThumbnailer.generate(@post.link)
                if @link.present?
                    image = ""
                    favicon = ""
                    title = ""
                    description = ""

                    if !@link.images.first.nil?
                        image = @link.images.first.src.to_s
                    end
                    if !@link.favicon.nil?
                        favicon = @link.favicon.to_s
                    end
                    if @link.title.present?
                        title = @link.title
                    end
                    if @link.description.present?
                        description = @link.description
                    end

                    @post_link = @post.post_links.create!(:image => image,
                                                            :favicon => favicon,
                                                            :title => title,
                                                            :description => description,
                                                            :post_id => @post.id)
                end
            end

            redirect_to post_path(@post)
        end
    end

    # PATCH/PUT /posts/1 or /posts/1.json
    def update
        if @post.update(post_params)
            if(params.has_key?(:post_images))
                params[:post_images]['image'].each do |a|
                    @post_image = @post.post_images.create!(:image => a, :post_id => @post.id)
                end
            end
        end
        redirect_to post_path(@post)
    end

    # DELETE /posts/1 or /posts/1.json
    def destroy
        @post.destroy
        respond_to do |format|
            format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
            format.json { head :no_content }
        end
    end

private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
        @post = Post.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
        params.require(:post).permit(:title, :content, :content_rich_text, :link, :podcast, :view_count, :post_shared_id, :share_count,
                                    :topic_list, :topic, { topic_ids: [] }, :topic_ids, 
                                    post_images_attributes: [:id, :post_id, :image])
    end
end

app/helpers/posts_helper.rb
module PostsHelper
include PostVotesHelper
include UsersHelper
    def cal_post_for_you_point(post)
        if(post.post_comments.count > 0)
            post_commments = post.post_comments.sort_by{|post_comment| post_comment.created_at}.reverse
            lastest_comment = post_commments.first
            comment_point = Time.now - lastest_comment.created_at
        else
            comment_point = Time.now - post.created_at
        end
        return comment_point
    end

    def cal_post_top_point(post)
        vote_count = count_post_vote(post)
        return vote_count
    end

    def cal_post_hot_point(post)
        vote_count = count_post_vote(post)
        comment_count = post.post_comments.count
        if post.view_count.present?
            view_count = post.view_count
        else
            view_count = 0
        end
        point = vote_count + view_count + comment_count
        return point
    end

    def cal_post_trend_point(post)
        comment_count = post.post_comments.count
        if post.view_count.present?
            view_count = post.view_count
        else
            view_count = 0
        end
        point = view_count + comment_count
        return point
    end

    def prepare_page_for_you
        # For logged in user
        processing_datas = []
        if user_signed_in?
            # Find post by followed user
            followed_users = current_user.followees
            followed_users.each do |followed_user|
                post_by_followed_users = find_owner_post_for_user(followed_user)
                post_by_followed_users.each do |post_by_followed_user|
                    processing_datas.push(post_by_followed_user)
                end
            end

            # Find post by followed topic
            followed_topics = find_owner_topic_follow_for_user(current_user)
            followed_topics.each do |followed_topic|
                post_by_followed_topics = followed_topic.posts
                post_by_followed_topics.each do |post_by_followed_topic|
                    processing_datas.push(post_by_followed_topic)
                end
            end

            # Remove duplicate data 
            processing_datas.uniq{ |post| [post.id]}

            # Sort data by lastest comment
            processing_datas = processing_datas.sort_by{|post| cal_post_for_you_point(post)}
        else
            # For 
            processing_datas = Post.all
            processing_datas = processing_datas.sort_by{|post| cal_post_for_you_point(post)}
        end

        return processing_datas
    end
end

app/views/posts/_form.html.erb
<div class="new_post_container">
    <div class="container">
        <div class="row">
            <div class="col-sm-8 col-nopadding">
                <div class="new_post_title">
                    <%if !@is_edit%>
                        <i><%= bootstrap_icon "pencil-square", width: 24, height: 24%></i>
                        <a>Bài viết mới</a>
                    <%else%>
                        <a>Update bài viết <%=@post.title%></a>
                    <%end%>
                </div>

                <div class="new_post_tab_link">
                    <ul class="nav nav-justified">
                        <li class="nav-item">
                            <%if @tab_id == "default" || @tab_id == "PostID"%>
                                <%active = "active"%>
                            <%else%> 
                                <%active = ""%>
                            <%end%>                                 
                            <a class="nav-link <%=active%>" href="<%=new_post_path(tab_id: 'PostID')%>"><i><%= bootstrap_icon "card-list", width: 20, height: 20%></i>Bài viết</a>
                        </li>
                        <li class="nav-item">
                            <%if @tab_id == "ImageID"%>
                                <%active = "active"%>
                            <%else%> 
                                <%active = ""%>
                            <%end%>                                     
                            <a class="nav-link <%=active%>" href="<%=new_post_path(tab_id: 'ImageID')%>"><i><%= bootstrap_icon "camera", width: 20, height: 20%></i>Hình ảnh</a>
                        </li>

                        <li class="nav-item">
                            <%if @tab_id == "LinkID"%>
                                <%active = "active"%>
                            <%else%> 
                                <%active = ""%>
                            <%end%>                                     
                            <a class="nav-link <%=active%>" href="<%=new_post_path(tab_id: 'LinkID')%>"><i><%= bootstrap_icon "link", width: 24, height: 24%></i>Link</a>
                        </li>

                        <li class="nav-item">
                            <%if @tab_id == "PodcastID"%>
                                <%active = "active"%>
                            <%else%> 
                                <%active = ""%>
                            <%end%>                                     
                            <a class="nav-link <%=active%>" href="<%=new_post_path(tab_id: 'PodcastID')%>"><i><%= bootstrap_icon "mic", width: 20, height: 20%></i>Podcast</a>
                        </li>
                    </ul>
                </div>

                <div class="new_post_tab_content">
                    <%@select_topic = find_owner_topic_follow_for_user(current_user)%>
                    <%= form_for @post, :html => { :class => "form-horizontal post" } do |f| %>
                        <div class="new_post_form">
                            <div class="new_post_section">
                                <div class="new_post_input">
                                    <%= f.text_field :title, :required => true, class: "form-control", placeholder: "Tiêu đề" %>
                                </div>
                            </div>
                        
                            <%if @tab_id == "default" || @tab_id == "PostID"%>
                                <div class="new_post_section">
                                    <div class="new_post_input">
                                        <%= f.rich_text_area :content_rich_text, class: "form-control-rich-text", placeholder: "Nội dung(tùy chọn)" %>
                                    </div>
                                </div>
                            <%end%>
                            
                            <%if @tab_id == "ImageID"%>
                                <div class="new_post_section">
                                    <div class="new_post_image_input">
                                        <%= f.file_field :image, :multiple => true, :id => "image_upload", name: "post_images[image][]"%>

                                        <div class="new_post_image_preview" id="result">
                                        </div>
                                    </div>
                                </div>
                                <script>
                                    window.onload = function(){
                                        //Check File API support
                                        if(window.File && window.FileList && window.FileReader)
                                        {
                                            var filesInput = document.getElementById("image_upload");
                                            
                                            filesInput.addEventListener("change", function(event){
                                                
                                                var files = event.target.files; //FileList object
                                                var output = document.getElementById("result");
                                                
                                                for(var i = 0; i< files.length; i++)
                                                {
                                                    var file = files[i];
                                                    
                                                    //Only pics
                                                    if(!file.type.match('image'))
                                                    continue;
                                                    
                                                    var picReader = new FileReader();
                                                    
                                                    picReader.addEventListener("load",function(event){
                                                        
                                                        var picFile = event.target;
                                                        
                                                        var div = document.createElement("div");
                                                        
                                                        div.innerHTML = "<img class='thumbnail' src='" + picFile.result + "'" +
                                                                "title='" + picFile.name + "'/>" + "<a href='#' class='new_post_image_preview_remove'>X</a>";
                                                        
                                                        output.insertBefore(div,null);   
                                                        div.children[1].addEventListener("click", function(event){
                                                            div.parentNode.removeChild(div);
                                                        });         
                                                    
                                                    });
                                                    
                                                    //Read the image
                                                    picReader.readAsDataURL(file);
                                                }                               
                                            
                                            });
                                        }
                                        else
                                        {
                                            console.log("Your browser does not support File API");
                                        }
                                    }
                                </script>
                            <%end%>

                            <%if @tab_id == "LinkID"%>
                                <div class="new_post_section">
                                    <div class="new_post_link_input">
                                        <%= f.text_area :link, :required => true, class: "form-control", placeholder: "Link"  %>
                                    </div>
                                </div>
                            <%end%>

                            <%if @tab_id == "PodcastID"%>
                                <div class="new_post_section">
                                    <div class="new_post_podcast_input">
                                        <%= f.file_field :podcast%>
                                    </div>
                                </div>
                            <%end%>
                        </div>
                            
                        <%if @select_topic.present?%>
                            <div class="new_post_topic_section">
                                <div class="new_post_topic_input">
                                    <%= f.select :topic_ids, 
                                                @select_topic.collect {|m| [m.name, m.id]}, 
                                                {:include_blank => true},
                                                {:required => true, :class => 'form-control new_post_topic_select'}%>   
                                </div>
                            </div>

                            <script>
								$(document).ready(function() {
									$('.new_post_topic_select').select2({
										placeholder: "-- Chọn chủ đề phù hợp --",
										allowClear: true,
										width: 'resolve',
										theme: "bootstrap-5",
										selectOnClose: true
									});
								});
							</script>
                        <%end%>
                            
                        <div class="new_post_submit">
                            <%= f.submit "Gửi bài viết", class: "new_post_form_submit" %>
                        </div>
                    <%end%>
                </div>
            </div>

            <div class="col-sm-4 col-nopadding">
                <div class="new_post_policy">
                    <div class="new_post_policy_title">
                        <a>Những lưu ý trước khi viết bài</a>
                    </div>
                    <div class="new_post_policy_content">
                        <div class="new_post_policy_content_index">
                            · Không sử dụng từ ngữ mang ý xúc phạm, miệt thị người khác
                        </div>
                        <div class="new_post_policy_content_index">
                            · Không sử dụng từ ngữ mang tính chất kích động, bạo lực
                        </div>
                        <div class="new_post_policy_content_index">
                            · Cư xử và hành động như những gì bạn làm ngoài đời thực
                        </div>
                        <div class="new_post_policy_content_index">
                            · Nhớ ghi nguồn nội dung bạn chia sẻ nếu có
                        </div>
                        <div class="new_post_policy_content_index">
                            · Không đăng tin sai sự thật, vi phạm pháp luật
                        </div>
                        <div class="new_post_policy_content_link">
                            Đọc các quy tắc khi tham gia cộng đồng tại
                            <a href="https://pollingu.com/posts/policy">thỏa thuận sử dụng </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>  
    </div>
</div>

app/views/posts/_post_share.html.erb
<div class='post_share_block' id="post_share_<%=@post_shared.id%>">
    <div class='post_share_info'>
        <%@owner_post_user = find_owner_user(@post_shared)%>
        <div class='post_share_info_left'>
            <%if @owner_post_user.avatar?%>
                <div class="post_share_user_avatar">
                    <%= link_to (image_tag(@owner_post_user.avatar.url)), image_path(url_for(@owner_post_user.avatar.url)), rel: "gallery" , :href => user_path(@owner_post_user)%>
                </div>
            <%else%>
                <div class="post_share_user_avatar">
                    <%= link_to (image_tag("default-user.png")), image_path(url_for("default-user.png")), rel: "gallery" , :href => user_path(@owner_post_user)%>
                </div>
            <%end%>
        </div>
        <div class='post_share_info_right'>
            <div class="post_share_user_name">
                <a><%= link_to @owner_post_user.name, user_path(@owner_post_user)%></a>
                <%if @owner_post_user.official%>
                    <i><%= bootstrap_icon "check-circle-fill", width: 14, height: 14, fill: '#5865f2'%></i>
                <%end%>
            </div>
            
            <div class="post_share_create">
                <span><%=@post_shared.created_at.strftime("%B %d")%> · <%=time_ago_in_words(@post_shared.created_at)%></span>
            </div>
        </div>
    </div>

    <div class='post_share_title'>
        <a><%= link_to (@post_shared.title), post_path(@post_shared) %></a>
    </div>

    <div class='post_share_content'>
        <a><%= truncate(strip_tags(@post_shared.content_rich_text.to_s), length: 300) %></a>
    </div>

    <%if @post_shared.post_images.count > 0 && @post_shared.post_images.count == 1%>
        <%@post_shared.post_images.each do |post_image|%>
            <div class='post_share_image'>
                <%= link_to (image_tag(post_image.image.url)), image_path(url_for(post_image.image.url)), rel: "gallery" , :href => post_path(@post_shared)%>
            </div>
        <%end%>
    <%elsif @post_shared.post_images.count > 1%>
        <div class='post_share_image'>
            <div id="carouselImageIndicators" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselImageIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselImageIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselImageIndicators" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img class="d-block w-100" src="<%=url_for(@post_shared.post_images.first.image.url)%>">
                    </div>
                    <%@post_shared.post_images.each do |post_image|%>
                        <div class="carousel-item">
                            <img class="d-block w-100" src="<%=url_for(post_image.image.url)%>">
                        </div>
                    <%end%>
                </div>
                <a class="carousel-control-prev" href="#carouselImageIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselImageIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
    <%end%>

    <%if @post_shared.post_links.count > 0%>
        <%@post_shared.post_links.each do |post_link|%>
            <div class='post_share_link_block'>
                <div class='post_share_link_image'>
                    <%= link_to (image_tag(post_link.image.to_s)), image_path(url_for(post_link.image.to_s)), rel: "gallery" , :href => url_for(@post_shared.link), target: :_blank%>
                </div>

                <div class='post_share_link_right'>
                    <div class='post_share_link_title'>
                        <a><%= link_to post_link.title, url_for(@post_shared.link), target: :_blank%></a>
                    </div>
                    <div class='post_share_link_description'>
                        <a><%= link_to truncate(strip_tags(post_link.description), length: 300), url_for(@post_shared.link), target: :_blank%></a>
                    </div>

                    <div class='post_share_link_url'>
                        <i><%= bootstrap_icon "link-45deg", width: 18, height: 18%></i>
                        <a><%= link_to get_domain_name(@post_shared.link.to_s), url_for(@post_shared.link), target: :_blank%></a>
                    </div>
                </div>
            </div>
        <%end%>
    <%end%>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/new.html.erb
<% content_for :meta_title, "Bài viết mới" %>

<%if @post_shared.present?%>
    <%= render 'share_form', post: @post %>
<%else%>
    <%= render 'form', post: @post %>
<%end%>

app/views/posts/show.js.erb
// Append new data
<%@post_comments.each do |post_comment|%>
  $("<%=j render post_comment %>").appendTo($("#post_show_comment_index_<%=@post.id%>"));
<%end%>

<%remain_item = @post_comments.total_count - (@post_comments.current_page * 10)%>
<%remain_item = "Xem thêm" + " " + remain_item.to_s + " " + "bình luận khác"%>

// Update pagination link
<% if @post_comments.last_page? %>
  $('#post_comment_pagination').remove();
<% else %>
  $('#post_comment_pagination').html("<%=j link_to_next_page(@post_comments, remain_item, :remote => true) %>");
<% end %>